/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FootprintsRouteImport } from './routes/footprints'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as UsageRouteImport } from './routes/usage'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as CharactersIdRouteImport } from './routes/characters/$id'
import { Route as CharactersNewRouteImport } from './routes/characters/new'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as DocumentsIdRouteImport } from './routes/documents.$id'
import { Route as ResourcesIndexRouteImport } from './routes/resources/index'
import { Route as ResourcesIdRouteImport } from './routes/resources/$id'
import { Route as ResourcesImportRouteImport } from './routes/resources/import'
import { Route as ResourcesNewRouteImport } from './routes/resources/new'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsAboutRouteImport } from './routes/settings/about'
import { Route as SettingsAppRouteImport } from './routes/settings/app'
import { Route as SettingsBackupsRouteImport } from './routes/settings/backups'
import { Route as SettingsCustomRouteImport } from './routes/settings/custom'
import { Route as SettingsDataRouteImport } from './routes/settings/data'
import { Route as SettingsDesktopRouteImport } from './routes/settings/desktop'
import { Route as SettingsPluginsRouteImport } from './routes/settings/plugins'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as SettingsSyncRouteImport } from './routes/settings/sync'
import { Route as CharactersIdIndexRouteImport } from './routes/characters/$id.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FootprintsRoute = FootprintsRouteImport.update({
  id: '/footprints',
  path: '/footprints',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const UsageRoute = UsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/characters/',
  path: '/characters/',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/characters/$id',
  path: '/characters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersNewRoute = CharactersNewRouteImport.update({
  id: '/characters/new',
  path: '/characters/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocumentsRoute,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIdRoute = ResourcesIdRouteImport.update({
  id: '/resources/$id',
  path: '/resources/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesImportRoute = ResourcesImportRouteImport.update({
  id: '/resources/import',
  path: '/resources/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesNewRoute = ResourcesNewRouteImport.update({
  id: '/resources/new',
  path: '/resources/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAboutRoute = SettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppRoute = SettingsAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBackupsRoute = SettingsBackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsCustomRoute = SettingsCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDataRoute = SettingsDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsDesktopRoute = SettingsDesktopRouteImport.update({
  id: '/desktop',
  path: '/desktop',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPluginsRoute = SettingsPluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsSyncRoute = SettingsSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => SettingsRoute,
} as any)
const CharactersIdIndexRoute = CharactersIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CharactersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/footprints': typeof FootprintsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/usage': typeof UsageRoute
  '/characters/$id': typeof CharactersIdRouteWithChildren
  '/characters/new': typeof CharactersNewRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/resources/import': typeof ResourcesImportRoute
  '/resources/new': typeof ResourcesNewRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/backups': typeof SettingsBackupsRoute
  '/settings/custom': typeof SettingsCustomRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/desktop': typeof SettingsDesktopRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/characters/': typeof CharactersIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/characters/$id/': typeof CharactersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/footprints': typeof FootprintsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/search': typeof SearchRoute
  '/stats': typeof StatsRoute
  '/usage': typeof UsageRoute
  '/characters/new': typeof CharactersNewRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/resources/import': typeof ResourcesImportRoute
  '/resources/new': typeof ResourcesNewRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/backups': typeof SettingsBackupsRoute
  '/settings/custom': typeof SettingsCustomRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/desktop': typeof SettingsDesktopRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/characters': typeof CharactersIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/resources': typeof ResourcesIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/characters/$id': typeof CharactersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/footprints': typeof FootprintsRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRouteWithChildren
  '/stats': typeof StatsRoute
  '/usage': typeof UsageRoute
  '/characters/$id': typeof CharactersIdRouteWithChildren
  '/characters/new': typeof CharactersNewRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/resources/$id': typeof ResourcesIdRoute
  '/resources/import': typeof ResourcesImportRoute
  '/resources/new': typeof ResourcesNewRoute
  '/settings/about': typeof SettingsAboutRoute
  '/settings/app': typeof SettingsAppRoute
  '/settings/backups': typeof SettingsBackupsRoute
  '/settings/custom': typeof SettingsCustomRoute
  '/settings/data': typeof SettingsDataRoute
  '/settings/desktop': typeof SettingsDesktopRoute
  '/settings/plugins': typeof SettingsPluginsRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/sync': typeof SettingsSyncRoute
  '/characters/': typeof CharactersIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/resources/': typeof ResourcesIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/characters/$id/': typeof CharactersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents'
    | '/footprints'
    | '/login'
    | '/messages'
    | '/search'
    | '/settings'
    | '/stats'
    | '/usage'
    | '/characters/$id'
    | '/characters/new'
    | '/documents/$id'
    | '/resources/$id'
    | '/resources/import'
    | '/resources/new'
    | '/settings/about'
    | '/settings/app'
    | '/settings/backups'
    | '/settings/custom'
    | '/settings/data'
    | '/settings/desktop'
    | '/settings/plugins'
    | '/settings/privacy'
    | '/settings/sync'
    | '/characters/'
    | '/documents/'
    | '/resources/'
    | '/settings/'
    | '/characters/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/footprints'
    | '/login'
    | '/messages'
    | '/search'
    | '/stats'
    | '/usage'
    | '/characters/new'
    | '/documents/$id'
    | '/resources/$id'
    | '/resources/import'
    | '/resources/new'
    | '/settings/about'
    | '/settings/app'
    | '/settings/backups'
    | '/settings/custom'
    | '/settings/data'
    | '/settings/desktop'
    | '/settings/plugins'
    | '/settings/privacy'
    | '/settings/sync'
    | '/characters'
    | '/documents'
    | '/resources'
    | '/settings'
    | '/characters/$id'
  id:
    | '__root__'
    | '/'
    | '/documents'
    | '/footprints'
    | '/login'
    | '/messages'
    | '/search'
    | '/settings'
    | '/stats'
    | '/usage'
    | '/characters/$id'
    | '/characters/new'
    | '/documents/$id'
    | '/resources/$id'
    | '/resources/import'
    | '/resources/new'
    | '/settings/about'
    | '/settings/app'
    | '/settings/backups'
    | '/settings/custom'
    | '/settings/data'
    | '/settings/desktop'
    | '/settings/plugins'
    | '/settings/privacy'
    | '/settings/sync'
    | '/characters/'
    | '/documents/'
    | '/resources/'
    | '/settings/'
    | '/characters/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  FootprintsRoute: typeof FootprintsRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  StatsRoute: typeof StatsRoute
  UsageRoute: typeof UsageRoute
  CharactersIdRoute: typeof CharactersIdRouteWithChildren
  CharactersNewRoute: typeof CharactersNewRoute
  ResourcesIdRoute: typeof ResourcesIdRoute
  ResourcesImportRoute: typeof ResourcesImportRoute
  ResourcesNewRoute: typeof ResourcesNewRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/footprints': {
      id: '/footprints'
      path: '/footprints'
      fullPath: '/footprints'
      preLoaderRoute: typeof FootprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usage': {
      id: '/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof UsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/characters/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/new': {
      id: '/characters/new'
      path: '/characters/new'
      fullPath: '/characters/new'
      preLoaderRoute: typeof CharactersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/$id': {
      id: '/resources/$id'
      path: '/resources/$id'
      fullPath: '/resources/$id'
      preLoaderRoute: typeof ResourcesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/import': {
      id: '/resources/import'
      path: '/resources/import'
      fullPath: '/resources/import'
      preLoaderRoute: typeof ResourcesImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/new': {
      id: '/resources/new'
      path: '/resources/new'
      fullPath: '/resources/new'
      preLoaderRoute: typeof ResourcesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/about': {
      id: '/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof SettingsAboutRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/app': {
      id: '/settings/app'
      path: '/app'
      fullPath: '/settings/app'
      preLoaderRoute: typeof SettingsAppRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/backups': {
      id: '/settings/backups'
      path: '/backups'
      fullPath: '/settings/backups'
      preLoaderRoute: typeof SettingsBackupsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/custom': {
      id: '/settings/custom'
      path: '/custom'
      fullPath: '/settings/custom'
      preLoaderRoute: typeof SettingsCustomRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/data': {
      id: '/settings/data'
      path: '/data'
      fullPath: '/settings/data'
      preLoaderRoute: typeof SettingsDataRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/desktop': {
      id: '/settings/desktop'
      path: '/desktop'
      fullPath: '/settings/desktop'
      preLoaderRoute: typeof SettingsDesktopRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/plugins': {
      id: '/settings/plugins'
      path: '/plugins'
      fullPath: '/settings/plugins'
      preLoaderRoute: typeof SettingsPluginsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/sync': {
      id: '/settings/sync'
      path: '/sync'
      fullPath: '/settings/sync'
      preLoaderRoute: typeof SettingsSyncRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/characters/$id/': {
      id: '/characters/$id/'
      path: '/'
      fullPath: '/characters/$id/'
      preLoaderRoute: typeof CharactersIdIndexRouteImport
      parentRoute: typeof CharactersIdRoute
    }
  }
}

interface DocumentsRouteChildren {
  DocumentsIdRoute: typeof DocumentsIdRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsIdRoute: DocumentsIdRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAboutRoute: typeof SettingsAboutRoute
  SettingsAppRoute: typeof SettingsAppRoute
  SettingsBackupsRoute: typeof SettingsBackupsRoute
  SettingsCustomRoute: typeof SettingsCustomRoute
  SettingsDataRoute: typeof SettingsDataRoute
  SettingsDesktopRoute: typeof SettingsDesktopRoute
  SettingsPluginsRoute: typeof SettingsPluginsRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsSyncRoute: typeof SettingsSyncRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAboutRoute: SettingsAboutRoute,
  SettingsAppRoute: SettingsAppRoute,
  SettingsBackupsRoute: SettingsBackupsRoute,
  SettingsCustomRoute: SettingsCustomRoute,
  SettingsDataRoute: SettingsDataRoute,
  SettingsDesktopRoute: SettingsDesktopRoute,
  SettingsPluginsRoute: SettingsPluginsRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsSyncRoute: SettingsSyncRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface CharactersIdRouteChildren {
  CharactersIdIndexRoute: typeof CharactersIdIndexRoute
}

const CharactersIdRouteChildren: CharactersIdRouteChildren = {
  CharactersIdIndexRoute: CharactersIdIndexRoute,
}

const CharactersIdRouteWithChildren = CharactersIdRoute._addFileChildren(
  CharactersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  FootprintsRoute: FootprintsRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRouteWithChildren,
  StatsRoute: StatsRoute,
  UsageRoute: UsageRoute,
  CharactersIdRoute: CharactersIdRouteWithChildren,
  CharactersNewRoute: CharactersNewRoute,
  ResourcesIdRoute: ResourcesIdRoute,
  ResourcesImportRoute: ResourcesImportRoute,
  ResourcesNewRoute: ResourcesNewRoute,
  CharactersIndexRoute: CharactersIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
