export const HIDDEN_SWITCH = "--hidden"

export const IPC = {
	windowMinimize: "desktop:window:minimize",
	windowToggleMaximize: "desktop:window:toggle-maximize",
	windowToggleDevTools: "desktop:window:toggle-devtools",
	windowClose: "desktop:window:close",
	windowIsMaximized: "desktop:window:is-maximized",
	windowMaximizedChanged: "desktop:window:maximized-changed",
	windowRetryLoad: "desktop:window:retry-load",
	updatesStatus: "desktop:updates:status",
	updatesChanged: "desktop:updates:changed",
	updatesCheck: "desktop:updates:check",
	updatesApply: "desktop:updates:apply",
	updatesQuitAndInstall: "desktop:updates:quit-and-install",
	pickLibraryFolder: "desktop:library:pick",
	relaunch: "desktop:relaunch",
	logsOpen: "desktop:logs:open",
	getConfig: "desktop:config:get",
	setConfig: "desktop:config:set",
	configSync: "desktop:config:sync",
	setCloseAction: "desktop:close-action:set",
	closeWithAction: "desktop:close-action:with",
	setLanguage: "desktop:config:set-language",
	getLanguage: "desktop:config:get-language",
	changeLibraryFolder: "desktop:library:change",
	setSharedFolderRoot: "desktop:shared-folder:set",
	setSharedFolderEnabled: "desktop:shared-folder:enabled",
	lanInfo: "desktop:lan:info",
	lanCheck: "desktop:lan:check",
	setLanEnabled: "desktop:lan:set-enabled",
	setLanPort: "desktop:lan:set-port",
	shellCacheSize: "desktop:shell-cache:size",
	shellCacheClear: "desktop:shell-cache:clear",
	completeWizard: "desktop:wizard:complete",
	wizardDefaults: "desktop:wizard:defaults",
	openExternal: "desktop:shell:open-external",
	appRoutes: "desktop:app:routes",
} as const
