// GENERATED by scripts/gen-sdk-deps.mjs — never hand-edit.
// The published SDK closure a scaffolded plugin can depend on; kept in
// lockstep with scripts/lib/sdk-closure.mjs (see sdks:pack).
export const SDK_DEP_NAMES: readonly string[] = [
	"@hoardodile/cli",
	"@hoardodile/host",
	"@hoardodile/host-web",
	"@hoardodile/i18n",
	"@hoardodile/sdk-react",
	"@hoardodile/sdk-server",
	"@hoardodile/sdk-types",
	"@hoardodile/sdk-web",
	"@hoardodile/ui",
	"@hoardodile/workbench",
]
