import { existsSync, readFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { describe, expect, it } from "vitest"

/**
 * The canonical template (`plugins/template`) is the single source of truth
 * for both the repo copy and the scaffolder's embedded copy
 * (`dist/template`, generated by scripts/copy-template.mjs). These guard the
 * root dotfiles a standalone plugin repo needs — a future edit must not
 * silently drop them, or a scaffolded plugin ships without the convention.
 *
 * Assert against `plugins/template` (like rewrite.test.ts reads its
 * package.json), not the `dist/` build artifact, which vitest excludes.
 */
const TEMPLATE_DIR = join(
	dirname(fileURLToPath(import.meta.url)),
	"..",
	"..",
	"template",
)

const templateFile = (name: string): string => join(TEMPLATE_DIR, name)

describe("template repo dotfiles", () => {
	it("ships .gitattributes", () => {
		expect(existsSync(templateFile(".gitattributes"))).toBe(true)
		expect(readFileSync(templateFile(".gitattributes"), "utf8")).toContain(
			"eol=lf",
		)
	})

	it("ships .editorconfig", () => {
		const editorconfig = templateFile(".editorconfig")
		expect(existsSync(editorconfig)).toBe(true)
		const content = readFileSync(editorconfig, "utf8")
		expect(content).toContain("root = true")
		expect(content).toContain("end_of_line = lf")
	})

	it("keeps the existing root dotfiles", () => {
		expect(existsSync(templateFile(".gitignore"))).toBe(true)
		expect(existsSync(templateFile(".nvmrc"))).toBe(true)
	})
})
